/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: 0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

// Request for creating an operation
type CreateOperationRequest struct {

	// The ID to use for this operation.
	OperationId string `json:"operationId,omitempty"`

	// The operation to create.
	Operation Operation `json:"operation,omitempty"`
}
