/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: 0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

// This represents a particular channel of distribution for a given package. e.g. Debian's jessie-backports dpkg mirror
type Distribution struct {

	// The cpe_uri in [cpe format](https://cpe.mitre.org/specification/) denoting the package manager version distributing a package.
	CpeUri string `json:"cpeUri,omitempty"`

	// The CPU architecture for which packages in this distribution channel were built
	Architecture string `json:"architecture,omitempty"`

	// The latest available version of this package in this distribution channel.
	LatestVersion Version `json:"latestVersion,omitempty"`

	// A freeform string denoting the maintainer of this package.
	Maintainer string `json:"maintainer,omitempty"`

	// The distribution channel-specific homepage for this package.
	Url string `json:"url,omitempty"`

	// The distribution channel-specific description of this package.
	Description string `json:"description,omitempty"`
}
