/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: 0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

// Container message for hash values.
type Hash struct {

	// The type of hash that was performed.
	Type_ string `json:"type,omitempty"`

	// The hash value.
	Value string `json:"value,omitempty"`
}
