/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: 0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

// Metadata for any related url information
type RelatedUrl struct {

	// Specific url to associate with the note
	Url string `json:"url,omitempty"`

	// Label to describe usage of the url
	Label string `json:"label,omitempty"`
}
