/*
 * Grafeas API
 *
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: 0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package api

// A SourceContext is a reference to a tree of files. A SourceContext together with a path point to a unique revision of a single file or directory.
type SourceContext struct {

	// A SourceContext referring to a revision in a cloud repo.
	CloudRepo CloudRepoSourceContext `json:"cloudRepo,omitempty"`

	// A SourceContext referring to a snapshot in a cloud workspace.
	CloudWorkspace CloudWorkspaceSourceContext `json:"cloudWorkspace,omitempty"`

	// A SourceContext referring to a Gerrit project.
	Gerrit GerritSourceContext `json:"gerrit,omitempty"`

	// A SourceContext referring to any third party Git repo (e.g. GitHub).
	Git GitSourceContext `json:"git,omitempty"`
}
