// Code generated by protoc-gen-go. DO NOT EDIT.
// source: intoto.proto

package intoto_go_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// This contains the fields corresponding to the definition of a software supply
// chain step in an in-toto layout. This information goes into a Grafeas note.
type InToto struct {
	// This field identifies the name of the step in the supply chain.
	StepName string `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	// This field contains the public keys that can be used to verify the
	// signatures on the step metadata.
	SigningKeys []*SigningKey `protobuf:"bytes,2,rep,name=signing_keys,json=signingKeys,proto3" json:"signing_keys,omitempty"`
	// The following fields contain in-toto artifact rules identifying the
	// artifacts that enter this supply chain step, and exit the supply chain
	// step, i.e. materials and products of the step.
	ExpectedMaterials []*InToto_ArtifactRule `protobuf:"bytes,3,rep,name=expected_materials,json=expectedMaterials,proto3" json:"expected_materials,omitempty"`
	ExpectedProducts  []*InToto_ArtifactRule `protobuf:"bytes,4,rep,name=expected_products,json=expectedProducts,proto3" json:"expected_products,omitempty"`
	// This field contains the expected command used to perform the step.
	ExpectedCommand []string `protobuf:"bytes,5,rep,name=expected_command,json=expectedCommand,proto3" json:"expected_command,omitempty"`
	// This field contains a value that indicates the minimum number of keys that
	// need to be used to sign the step's in-toto link.
	Threshold            int64    `protobuf:"varint,6,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InToto) Reset()         { *m = InToto{} }
func (m *InToto) String() string { return proto.CompactTextString(m) }
func (*InToto) ProtoMessage()    {}
func (*InToto) Descriptor() ([]byte, []int) {
	return fileDescriptor_1442eade79a66571, []int{0}
}

func (m *InToto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InToto.Unmarshal(m, b)
}
func (m *InToto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InToto.Marshal(b, m, deterministic)
}
func (m *InToto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InToto.Merge(m, src)
}
func (m *InToto) XXX_Size() int {
	return xxx_messageInfo_InToto.Size(m)
}
func (m *InToto) XXX_DiscardUnknown() {
	xxx_messageInfo_InToto.DiscardUnknown(m)
}

var xxx_messageInfo_InToto proto.InternalMessageInfo

func (m *InToto) GetStepName() string {
	if m != nil {
		return m.StepName
	}
	return ""
}

func (m *InToto) GetSigningKeys() []*SigningKey {
	if m != nil {
		return m.SigningKeys
	}
	return nil
}

func (m *InToto) GetExpectedMaterials() []*InToto_ArtifactRule {
	if m != nil {
		return m.ExpectedMaterials
	}
	return nil
}

func (m *InToto) GetExpectedProducts() []*InToto_ArtifactRule {
	if m != nil {
		return m.ExpectedProducts
	}
	return nil
}

func (m *InToto) GetExpectedCommand() []string {
	if m != nil {
		return m.ExpectedCommand
	}
	return nil
}

func (m *InToto) GetThreshold() int64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

// Defines an object to declare an in-toto artifact rule
type InToto_ArtifactRule struct {
	ArtifactRule         []string `protobuf:"bytes,1,rep,name=artifact_rule,json=artifactRule,proto3" json:"artifact_rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InToto_ArtifactRule) Reset()         { *m = InToto_ArtifactRule{} }
func (m *InToto_ArtifactRule) String() string { return proto.CompactTextString(m) }
func (*InToto_ArtifactRule) ProtoMessage()    {}
func (*InToto_ArtifactRule) Descriptor() ([]byte, []int) {
	return fileDescriptor_1442eade79a66571, []int{0, 0}
}

func (m *InToto_ArtifactRule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InToto_ArtifactRule.Unmarshal(m, b)
}
func (m *InToto_ArtifactRule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InToto_ArtifactRule.Marshal(b, m, deterministic)
}
func (m *InToto_ArtifactRule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InToto_ArtifactRule.Merge(m, src)
}
func (m *InToto_ArtifactRule) XXX_Size() int {
	return xxx_messageInfo_InToto_ArtifactRule.Size(m)
}
func (m *InToto_ArtifactRule) XXX_DiscardUnknown() {
	xxx_messageInfo_InToto_ArtifactRule.DiscardUnknown(m)
}

var xxx_messageInfo_InToto_ArtifactRule proto.InternalMessageInfo

func (m *InToto_ArtifactRule) GetArtifactRule() []string {
	if m != nil {
		return m.ArtifactRule
	}
	return nil
}

// This defines the format used to record keys used in the software supply
// chain. An in-toto link is attested using one or more keys defined in the
// in-toto layout.
type SigningKey struct {
	// key_id is an identifier for the signing key.
	KeyId string `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// This field identifies the hash algorithms used in the particular key ID.
	KeyIdHashAlgorithms []string `protobuf:"bytes,2,rep,name=key_id_hash_algorithms,json=keyIdHashAlgorithms,proto3" json:"key_id_hash_algorithms,omitempty"`
	// This field identifies the specific signing method. Eg: "RSASSA-PSS",
	// "ed25519", and "ecdsa".
	KeyType string `protobuf:"bytes,3,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	// This field contains the actual public key.
	PublicKeyValue string `protobuf:"bytes,4,opt,name=public_key_value,json=publicKeyValue,proto3" json:"public_key_value,omitempty"`
	// This field contains the overall scheme used for the creation of the signing
	// key. Eg: "rsassa-pss-sha256".
	KeyScheme            string   `protobuf:"bytes,5,opt,name=key_scheme,json=keyScheme,proto3" json:"key_scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SigningKey) Reset()         { *m = SigningKey{} }
func (m *SigningKey) String() string { return proto.CompactTextString(m) }
func (*SigningKey) ProtoMessage()    {}
func (*SigningKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_1442eade79a66571, []int{1}
}

func (m *SigningKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SigningKey.Unmarshal(m, b)
}
func (m *SigningKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SigningKey.Marshal(b, m, deterministic)
}
func (m *SigningKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SigningKey.Merge(m, src)
}
func (m *SigningKey) XXX_Size() int {
	return xxx_messageInfo_SigningKey.Size(m)
}
func (m *SigningKey) XXX_DiscardUnknown() {
	xxx_messageInfo_SigningKey.DiscardUnknown(m)
}

var xxx_messageInfo_SigningKey proto.InternalMessageInfo

func (m *SigningKey) GetKeyId() string {
	if m != nil {
		return m.KeyId
	}
	return ""
}

func (m *SigningKey) GetKeyIdHashAlgorithms() []string {
	if m != nil {
		return m.KeyIdHashAlgorithms
	}
	return nil
}

func (m *SigningKey) GetKeyType() string {
	if m != nil {
		return m.KeyType
	}
	return ""
}

func (m *SigningKey) GetPublicKeyValue() string {
	if m != nil {
		return m.PublicKeyValue
	}
	return ""
}

func (m *SigningKey) GetKeyScheme() string {
	if m != nil {
		return m.KeyScheme
	}
	return ""
}

// This corresponds to a signed in-toto link - it is made up of one or more
// signatures and the in-toto link itself. This is used for occurrences of a
// Grafeas in-toto note.
type Details struct {
	Signatures           []*Signature `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	Link                 *Link        `protobuf:"bytes,2,opt,name=link,json=signed,proto3" json:"link,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Details) Reset()         { *m = Details{} }
func (m *Details) String() string { return proto.CompactTextString(m) }
func (*Details) ProtoMessage()    {}
func (*Details) Descriptor() ([]byte, []int) {
	return fileDescriptor_1442eade79a66571, []int{2}
}

func (m *Details) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Details.Unmarshal(m, b)
}
func (m *Details) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Details.Marshal(b, m, deterministic)
}
func (m *Details) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Details.Merge(m, src)
}
func (m *Details) XXX_Size() int {
	return xxx_messageInfo_Details.Size(m)
}
func (m *Details) XXX_DiscardUnknown() {
	xxx_messageInfo_Details.DiscardUnknown(m)
}

var xxx_messageInfo_Details proto.InternalMessageInfo

func (m *Details) GetSignatures() []*Signature {
	if m != nil {
		return m.Signatures
	}
	return nil
}

func (m *Details) GetLink() *Link {
	if m != nil {
		return m.Link
	}
	return nil
}

// A signature object consists of the KeyID used and the signature itself.
type Signature struct {
	KeyId                string   `protobuf:"bytes,1,opt,name=key_id,json=keyid,proto3" json:"key_id,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,json=sig,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_1442eade79a66571, []int{3}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetKeyId() string {
	if m != nil {
		return m.KeyId
	}
	return ""
}

func (m *Signature) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

// This corresponds to an in-toto link.
type Link struct {
	// This field contains the full command executed for the step. This can also
	// be empty if links are generated for operations that aren't directly mapped
	// to a specific command. Each term in the command is an independent string
	// in the list. An example of a command in the in-toto metadata field is:
	// "command": ["git", "clone", "https://github.com/in-toto/demo-project.git"]
	EffectiveCommand []string `protobuf:"bytes,1,rep,name=effective_command,json=command,proto3" json:"effective_command,omitempty"`
	// Materials are the supply chain artifacts that go into the step and are used
	// for the operation performed. The key of the map is the path of the artifact
	// and the structure contains the recorded hash information. An example is:
	// "materials": [
	//   {
	//     "resource_uri": "foo/bar",
	//     "hashes": {
	//       "sha256": "ebebf...",
	//       <OTHER HASH ALGORITHMS>: <HASH VALUE>
	//     }
	//   }
	// ]
	Materials []*Link_Artifact `protobuf:"bytes,2,rep,name=materials,proto3" json:"materials,omitempty"`
	// Products are the supply chain artifacts generated as a result of the step.
	// The structure is identical to that of materials.
	Products []*Link_Artifact `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	// By Products are data generated as part of a software supply chain step, but
	// are not the actual result of the step. The suggested fields are "stderr",
	// "stdout", and "return-value".
	Byproducts *Link_ByProducts `protobuf:"bytes,4,opt,name=byproducts,proto3" json:"byproducts,omitempty"`
	// This is a field that can be used to capture information about the
	// environment. It is suggested for this field to contain information that
	// details environment variables, filesystem information, and the present
	// working directory. The recommended structure of this field is:
	// "environment": {
	//   "custom_values": {
	//     "variables": "<ENV>",
	//     "filesystem": "<FS>",
	//     "workdir": "<CWD>",
	//     "<ANY OTHER RELEVANT FIELDS>": "..."
	//   }
	// }
	Environment          *Link_Environment `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Link) Reset()         { *m = Link{} }
func (m *Link) String() string { return proto.CompactTextString(m) }
func (*Link) ProtoMessage()    {}
func (*Link) Descriptor() ([]byte, []int) {
	return fileDescriptor_1442eade79a66571, []int{4}
}

func (m *Link) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link.Unmarshal(m, b)
}
func (m *Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link.Marshal(b, m, deterministic)
}
func (m *Link) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link.Merge(m, src)
}
func (m *Link) XXX_Size() int {
	return xxx_messageInfo_Link.Size(m)
}
func (m *Link) XXX_DiscardUnknown() {
	xxx_messageInfo_Link.DiscardUnknown(m)
}

var xxx_messageInfo_Link proto.InternalMessageInfo

func (m *Link) GetEffectiveCommand() []string {
	if m != nil {
		return m.EffectiveCommand
	}
	return nil
}

func (m *Link) GetMaterials() []*Link_Artifact {
	if m != nil {
		return m.Materials
	}
	return nil
}

func (m *Link) GetProducts() []*Link_Artifact {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Link) GetByproducts() *Link_ByProducts {
	if m != nil {
		return m.Byproducts
	}
	return nil
}

func (m *Link) GetEnvironment() *Link_Environment {
	if m != nil {
		return m.Environment
	}
	return nil
}

// Defines a hash object for use in Materials and Products.
type Link_ArtifactHash struct {
	Sha256               string   `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Link_ArtifactHash) Reset()         { *m = Link_ArtifactHash{} }
func (m *Link_ArtifactHash) String() string { return proto.CompactTextString(m) }
func (*Link_ArtifactHash) ProtoMessage()    {}
func (*Link_ArtifactHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_1442eade79a66571, []int{4, 0}
}

func (m *Link_ArtifactHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link_ArtifactHash.Unmarshal(m, b)
}
func (m *Link_ArtifactHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link_ArtifactHash.Marshal(b, m, deterministic)
}
func (m *Link_ArtifactHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link_ArtifactHash.Merge(m, src)
}
func (m *Link_ArtifactHash) XXX_Size() int {
	return xxx_messageInfo_Link_ArtifactHash.Size(m)
}
func (m *Link_ArtifactHash) XXX_DiscardUnknown() {
	xxx_messageInfo_Link_ArtifactHash.DiscardUnknown(m)
}

var xxx_messageInfo_Link_ArtifactHash proto.InternalMessageInfo

func (m *Link_ArtifactHash) GetSha256() string {
	if m != nil {
		return m.Sha256
	}
	return ""
}

type Link_Artifact struct {
	ResourceUri          string             `protobuf:"bytes,1,opt,name=resource_uri,json=resourceUri,proto3" json:"resource_uri,omitempty"`
	Hashes               *Link_ArtifactHash `protobuf:"bytes,2,opt,name=hashes,proto3" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Link_Artifact) Reset()         { *m = Link_Artifact{} }
func (m *Link_Artifact) String() string { return proto.CompactTextString(m) }
func (*Link_Artifact) ProtoMessage()    {}
func (*Link_Artifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_1442eade79a66571, []int{4, 1}
}

func (m *Link_Artifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link_Artifact.Unmarshal(m, b)
}
func (m *Link_Artifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link_Artifact.Marshal(b, m, deterministic)
}
func (m *Link_Artifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link_Artifact.Merge(m, src)
}
func (m *Link_Artifact) XXX_Size() int {
	return xxx_messageInfo_Link_Artifact.Size(m)
}
func (m *Link_Artifact) XXX_DiscardUnknown() {
	xxx_messageInfo_Link_Artifact.DiscardUnknown(m)
}

var xxx_messageInfo_Link_Artifact proto.InternalMessageInfo

func (m *Link_Artifact) GetResourceUri() string {
	if m != nil {
		return m.ResourceUri
	}
	return ""
}

func (m *Link_Artifact) GetHashes() *Link_ArtifactHash {
	if m != nil {
		return m.Hashes
	}
	return nil
}

// Defines an object for the byproducts field in in-toto links.
type Link_ByProducts struct {
	CustomValues         map[string]string `protobuf:"bytes,1,rep,name=custom_values,json=customValues,proto3" json:"custom_values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Link_ByProducts) Reset()         { *m = Link_ByProducts{} }
func (m *Link_ByProducts) String() string { return proto.CompactTextString(m) }
func (*Link_ByProducts) ProtoMessage()    {}
func (*Link_ByProducts) Descriptor() ([]byte, []int) {
	return fileDescriptor_1442eade79a66571, []int{4, 2}
}

func (m *Link_ByProducts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link_ByProducts.Unmarshal(m, b)
}
func (m *Link_ByProducts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link_ByProducts.Marshal(b, m, deterministic)
}
func (m *Link_ByProducts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link_ByProducts.Merge(m, src)
}
func (m *Link_ByProducts) XXX_Size() int {
	return xxx_messageInfo_Link_ByProducts.Size(m)
}
func (m *Link_ByProducts) XXX_DiscardUnknown() {
	xxx_messageInfo_Link_ByProducts.DiscardUnknown(m)
}

var xxx_messageInfo_Link_ByProducts proto.InternalMessageInfo

func (m *Link_ByProducts) GetCustomValues() map[string]string {
	if m != nil {
		return m.CustomValues
	}
	return nil
}

// Defines an object for the environment field in in-toto links.
type Link_Environment struct {
	CustomValues         map[string]string `protobuf:"bytes,1,rep,name=custom_values,json=customValues,proto3" json:"custom_values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Link_Environment) Reset()         { *m = Link_Environment{} }
func (m *Link_Environment) String() string { return proto.CompactTextString(m) }
func (*Link_Environment) ProtoMessage()    {}
func (*Link_Environment) Descriptor() ([]byte, []int) {
	return fileDescriptor_1442eade79a66571, []int{4, 3}
}

func (m *Link_Environment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Link_Environment.Unmarshal(m, b)
}
func (m *Link_Environment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Link_Environment.Marshal(b, m, deterministic)
}
func (m *Link_Environment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Link_Environment.Merge(m, src)
}
func (m *Link_Environment) XXX_Size() int {
	return xxx_messageInfo_Link_Environment.Size(m)
}
func (m *Link_Environment) XXX_DiscardUnknown() {
	xxx_messageInfo_Link_Environment.DiscardUnknown(m)
}

var xxx_messageInfo_Link_Environment proto.InternalMessageInfo

func (m *Link_Environment) GetCustomValues() map[string]string {
	if m != nil {
		return m.CustomValues
	}
	return nil
}

func init() {
	proto.RegisterType((*InToto)(nil), "grafeas.v1beta1.intoto.InToto")
	proto.RegisterType((*InToto_ArtifactRule)(nil), "grafeas.v1beta1.intoto.InToto.ArtifactRule")
	proto.RegisterType((*SigningKey)(nil), "grafeas.v1beta1.intoto.SigningKey")
	proto.RegisterType((*Details)(nil), "grafeas.v1beta1.intoto.Details")
	proto.RegisterType((*Signature)(nil), "grafeas.v1beta1.intoto.Signature")
	proto.RegisterType((*Link)(nil), "grafeas.v1beta1.intoto.Link")
	proto.RegisterType((*Link_ArtifactHash)(nil), "grafeas.v1beta1.intoto.Link.ArtifactHash")
	proto.RegisterType((*Link_Artifact)(nil), "grafeas.v1beta1.intoto.Link.Artifact")
	proto.RegisterType((*Link_ByProducts)(nil), "grafeas.v1beta1.intoto.Link.ByProducts")
	proto.RegisterMapType((map[string]string)(nil), "grafeas.v1beta1.intoto.Link.ByProducts.CustomValuesEntry")
	proto.RegisterType((*Link_Environment)(nil), "grafeas.v1beta1.intoto.Link.Environment")
	proto.RegisterMapType((map[string]string)(nil), "grafeas.v1beta1.intoto.Link.Environment.CustomValuesEntry")
}

func init() { proto.RegisterFile("intoto.proto", fileDescriptor_1442eade79a66571) }

var fileDescriptor_1442eade79a66571 = []byte{
	// 753 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x5d, 0x6f, 0xe3, 0x44,
	0x14, 0x95, 0xe3, 0xc4, 0x8d, 0xaf, 0xb3, 0xd0, 0x0e, 0x10, 0x79, 0xc3, 0x22, 0x65, 0x83, 0x80,
	0xac, 0x90, 0x5c, 0x6d, 0x2a, 0xd0, 0xd2, 0x17, 0x94, 0x2d, 0xd5, 0xb2, 0x2c, 0xa0, 0x95, 0xb7,
	0x20, 0x54, 0x09, 0xac, 0x89, 0x7d, 0x13, 0x8f, 0xfc, 0x29, 0xcf, 0x38, 0xc2, 0x6f, 0xfc, 0x14,
	0xc4, 0x3b, 0xe2, 0x0f, 0xf0, 0xc6, 0x1f, 0x43, 0xe3, 0x6f, 0x89, 0x36, 0x6a, 0x1f, 0x78, 0x8a,
	0xef, 0xf1, 0x39, 0xc7, 0x77, 0xee, 0x3d, 0xa3, 0xc0, 0x84, 0xc5, 0x22, 0x11, 0x89, 0x95, 0x66,
	0x89, 0x48, 0xc8, 0x74, 0x97, 0xd1, 0x2d, 0x52, 0x6e, 0xed, 0x9f, 0x6e, 0x50, 0xd0, 0xa7, 0x56,
	0xf5, 0x76, 0xf1, 0xbb, 0x0a, 0xda, 0xcb, 0xf8, 0x4a, 0x52, 0xde, 0x07, 0x9d, 0x0b, 0x4c, 0x9d,
	0x98, 0x46, 0x68, 0x2a, 0x73, 0x65, 0xa9, 0xdb, 0x63, 0x09, 0x7c, 0x4f, 0x23, 0x24, 0x97, 0x30,
	0xe1, 0x6c, 0x17, 0xb3, 0x78, 0xe7, 0x04, 0x58, 0x70, 0x73, 0x30, 0x57, 0x97, 0xc6, 0x6a, 0x61,
	0xdd, 0x6c, 0x6b, 0xbd, 0xa9, 0xb8, 0xaf, 0xb0, 0xb0, 0x0d, 0xde, 0x3e, 0x73, 0x72, 0x0d, 0x04,
	0x7f, 0x4d, 0xd1, 0x15, 0xe8, 0x39, 0x11, 0x15, 0x98, 0x31, 0x1a, 0x72, 0x53, 0x2d, 0xcd, 0x3e,
	0xbd, 0xcd, 0xac, 0xea, 0xcf, 0x5a, 0x67, 0x82, 0x6d, 0xa9, 0x2b, 0xec, 0x3c, 0x44, 0xfb, 0xa4,
	0xb1, 0xf9, 0xae, 0x71, 0x21, 0x3f, 0x41, 0x0b, 0x3a, 0x69, 0x96, 0x78, 0xb9, 0x2b, 0xb8, 0x39,
	0xbc, 0xbf, 0xf5, 0x71, 0xe3, 0xf2, 0xba, 0x36, 0x21, 0x4f, 0xa0, 0xc5, 0x1c, 0x37, 0x89, 0x22,
	0x1a, 0x7b, 0xe6, 0x68, 0xae, 0x2e, 0x75, 0xfb, 0xed, 0x06, 0xbf, 0xa8, 0x60, 0xf2, 0x08, 0x74,
	0xe1, 0x67, 0xc8, 0xfd, 0x24, 0xf4, 0x4c, 0x6d, 0xae, 0x2c, 0x55, 0xbb, 0x03, 0x66, 0x67, 0x30,
	0xe9, 0x7f, 0x8a, 0x7c, 0x08, 0x0f, 0x68, 0x5d, 0x3b, 0x59, 0x1e, 0xca, 0xb1, 0x4b, 0xd7, 0x09,
	0xed, 0x91, 0x16, 0x7f, 0x2b, 0x00, 0xdd, 0x3c, 0xc9, 0x7b, 0xa0, 0x05, 0x58, 0x38, 0xcc, 0xab,
	0x77, 0x34, 0x0a, 0xb0, 0x78, 0xe9, 0x91, 0x33, 0x98, 0x56, 0xb0, 0xe3, 0x53, 0xee, 0x3b, 0x34,
	0xdc, 0x25, 0x19, 0x13, 0x7e, 0x54, 0xad, 0x4a, 0xb7, 0xdf, 0x29, 0x69, 0x5f, 0x53, 0xee, 0xaf,
	0xdb, 0x57, 0xe4, 0x21, 0x8c, 0xa5, 0x48, 0x14, 0x29, 0x9a, 0x6a, 0xe9, 0x76, 0x14, 0x60, 0x71,
	0x55, 0xa4, 0x48, 0x96, 0x70, 0x9c, 0xe6, 0x9b, 0x90, 0xb9, 0x72, 0xdf, 0xce, 0x9e, 0x86, 0x39,
	0x9a, 0xc3, 0x92, 0xf2, 0x56, 0x85, 0xbf, 0xc2, 0xe2, 0x47, 0x89, 0x92, 0x0f, 0x00, 0x24, 0x85,
	0xbb, 0x3e, 0x46, 0x68, 0x8e, 0x4a, 0x8e, 0x1e, 0x60, 0xf1, 0xa6, 0x04, 0x16, 0xbf, 0x29, 0x70,
	0xf4, 0x15, 0x0a, 0xca, 0x42, 0x4e, 0xd6, 0x00, 0x32, 0x0d, 0x54, 0xe4, 0x19, 0xf2, 0xf2, 0xb0,
	0xc6, 0xea, 0xf1, 0xa1, 0x0c, 0x95, 0x4c, 0xbb, 0x27, 0x22, 0x2b, 0x18, 0x86, 0x2c, 0x0e, 0xcc,
	0xc1, 0x5c, 0x59, 0x1a, 0xab, 0x47, 0xb7, 0x89, 0xbf, 0x65, 0x71, 0x60, 0x6b, 0x52, 0x87, 0xde,
	0xe2, 0x1c, 0xf4, 0xd6, 0xec, 0xc6, 0xf9, 0x31, 0x8f, 0x4c, 0x41, 0x6f, 0xbf, 0x52, 0x9a, 0xeb,
	0xb6, 0xca, 0xd9, 0x6e, 0xf1, 0x8f, 0x06, 0x43, 0x69, 0x46, 0x16, 0x70, 0x82, 0xdb, 0x2d, 0xba,
	0x82, 0xed, 0xb1, 0x4d, 0x41, 0xb5, 0xaf, 0xa3, 0xba, 0x24, 0x17, 0xa0, 0x77, 0xa9, 0xae, 0xae,
	0xc8, 0x47, 0x87, 0x3a, 0xec, 0x82, 0xd7, 0xe9, 0xc8, 0x1a, 0xc6, 0x6d, 0x7c, 0xd5, 0xfb, 0x78,
	0xb4, 0x32, 0xf2, 0x02, 0x60, 0x53, 0xf4, 0xee, 0x80, 0x1c, 0xd5, 0x27, 0x07, 0x4d, 0x9e, 0x17,
	0x4d, 0xda, 0xed, 0x9e, 0x94, 0x7c, 0x03, 0x06, 0xc6, 0x7b, 0x96, 0x25, 0x71, 0x84, 0xb1, 0x28,
	0x97, 0x6b, 0xac, 0x96, 0x07, 0x9d, 0x2e, 0x3b, 0xbe, 0xdd, 0x17, 0xcf, 0x3e, 0xee, 0xc2, 0x2f,
	0x63, 0x48, 0xa6, 0xa0, 0x71, 0x9f, 0xae, 0x3e, 0xfb, 0xbc, 0x5e, 0x44, 0x5d, 0xcd, 0x52, 0x18,
	0x37, 0x3c, 0xf2, 0x18, 0x26, 0x19, 0xf2, 0x24, 0xcf, 0x5c, 0x74, 0xf2, 0x8c, 0xd5, 0x4c, 0xa3,
	0xc1, 0x7e, 0xc8, 0x18, 0x59, 0x83, 0x26, 0x13, 0x8f, 0xbc, 0x8e, 0xc4, 0x93, 0x3b, 0x0d, 0x4b,
	0x76, 0x60, 0xd7, 0xc2, 0xd9, 0x9f, 0x0a, 0x40, 0x37, 0x00, 0xf2, 0x0b, 0x3c, 0x70, 0x73, 0x2e,
	0x92, 0xa8, 0x8a, 0x7d, 0x13, 0xd4, 0x2f, 0xee, 0x38, 0x40, 0xeb, 0xa2, 0x14, 0x97, 0x97, 0x83,
	0x5f, 0xc6, 0x22, 0x2b, 0xec, 0x89, 0xdb, 0x83, 0x66, 0x5f, 0xc2, 0xc9, 0x7f, 0x28, 0xe4, 0x18,
	0xd4, 0x00, 0x8b, 0xfa, 0x80, 0xf2, 0x91, 0xbc, 0x0b, 0xa3, 0xea, 0xda, 0x55, 0x69, 0xac, 0x8a,
	0xf3, 0xc1, 0x33, 0x65, 0xf6, 0x97, 0x02, 0x46, 0x6f, 0xcc, 0xc4, 0xb9, 0xb9, 0xe1, 0xf3, 0xbb,
	0xee, 0xe9, 0x7f, 0xef, 0xf8, 0xf9, 0xcf, 0xf0, 0x90, 0x25, 0xb7, 0xb4, 0xf3, 0x5a, 0xb9, 0x7e,
	0xb6, 0x63, 0xc2, 0xcf, 0x37, 0x96, 0x9b, 0x44, 0xa7, 0x35, 0xa9, 0xfd, 0x2d, 0xff, 0xbf, 0x4e,
	0x6b, 0xc9, 0x69, 0x25, 0x71, 0x76, 0x89, 0x53, 0xe2, 0x7f, 0x0c, 0xd4, 0x17, 0xf6, 0x7a, 0xa3,
	0x95, 0xc5, 0xd9, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x30, 0xd3, 0xf4, 0x56, 0xf4, 0x06, 0x00,
	0x00,
}
