/**
 * Grafeas API
 * An API to insert and retrieve annotations on cloud artifacts.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package java.io.grafeas.client;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.grafeas.client.Note;
import java.util.ArrayList;
import java.util.List;


/**
 * Response including listed notes.
 */
@ApiModel(description = "Response including listed notes.")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-08T12:57:49.437-04:00")
public class ListNotesResponse   {
  @SerializedName("notes")
  private List<Note> notes = new ArrayList<Note>();

  @SerializedName("nextPageToken")
  private String nextPageToken = null;

  public ListNotesResponse notes(List<Note> notes) {
    this.notes = notes;
    return this;
  }

  public ListNotesResponse addNotesItem(Note notesItem) {
    this.notes.add(notesItem);
    return this;
  }

   /**
   * The occurrences requested
   * @return notes
  **/
  @ApiModelProperty(example = "null", value = "The occurrences requested")
  public List<Note> getNotes() {
    return notes;
  }

  public void setNotes(List<Note> notes) {
    this.notes = notes;
  }

  public ListNotesResponse nextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

   /**
   * The next pagination token in the List response. It should be used as page_token for the following request. An empty value means no more result.
   * @return nextPageToken
  **/
  @ApiModelProperty(example = "null", value = "The next pagination token in the List response. It should be used as page_token for the following request. An empty value means no more result.")
  public String getNextPageToken() {
    return nextPageToken;
  }

  public void setNextPageToken(String nextPageToken) {
    this.nextPageToken = nextPageToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListNotesResponse listNotesResponse = (ListNotesResponse) o;
    return Objects.equals(this.notes, listNotesResponse.notes) &&
        Objects.equals(this.nextPageToken, listNotesResponse.nextPageToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(notes, nextPageToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListNotesResponse {\n");
    
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    nextPageToken: ").append(toIndentedString(nextPageToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

