// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/discovery.proto

package discovery_go_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	common_go_proto "github.com/grafeas/grafeas/proto/v1/common_go_proto"
	status "google.golang.org/genproto/googleapis/rpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Whether the resource is continuously analyzed.
type Discovered_ContinuousAnalysis int32

const (
	// Unknown.
	Discovered_CONTINUOUS_ANALYSIS_UNSPECIFIED Discovered_ContinuousAnalysis = 0
	// The resource is continuously analyzed.
	Discovered_ACTIVE Discovered_ContinuousAnalysis = 1
	// The resource is ignored for continuous analysis.
	Discovered_INACTIVE Discovered_ContinuousAnalysis = 2
)

var Discovered_ContinuousAnalysis_name = map[int32]string{
	0: "CONTINUOUS_ANALYSIS_UNSPECIFIED",
	1: "ACTIVE",
	2: "INACTIVE",
}

var Discovered_ContinuousAnalysis_value = map[string]int32{
	"CONTINUOUS_ANALYSIS_UNSPECIFIED": 0,
	"ACTIVE":                          1,
	"INACTIVE":                        2,
}

func (x Discovered_ContinuousAnalysis) String() string {
	return proto.EnumName(Discovered_ContinuousAnalysis_name, int32(x))
}

func (Discovered_ContinuousAnalysis) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_046437f686d0269e, []int{2, 0}
}

// Analysis status for a resource. Currently for initial analysis only (not
// updated in continuous analysis).
type Discovered_AnalysisStatus int32

const (
	// Unknown.
	Discovered_ANALYSIS_STATUS_UNSPECIFIED Discovered_AnalysisStatus = 0
	// Resource is known but no action has been taken yet.
	Discovered_PENDING Discovered_AnalysisStatus = 1
	// Resource is being analyzed.
	Discovered_SCANNING Discovered_AnalysisStatus = 2
	// Analysis has finished successfully.
	Discovered_FINISHED_SUCCESS Discovered_AnalysisStatus = 3
	// Analysis has finished unsuccessfully, the analysis itself is in a bad
	// state.
	Discovered_FINISHED_FAILED Discovered_AnalysisStatus = 4
	// The resource is known not to be supported
	Discovered_FINISHED_UNSUPPORTED Discovered_AnalysisStatus = 5
)

var Discovered_AnalysisStatus_name = map[int32]string{
	0: "ANALYSIS_STATUS_UNSPECIFIED",
	1: "PENDING",
	2: "SCANNING",
	3: "FINISHED_SUCCESS",
	4: "FINISHED_FAILED",
	5: "FINISHED_UNSUPPORTED",
}

var Discovered_AnalysisStatus_value = map[string]int32{
	"ANALYSIS_STATUS_UNSPECIFIED": 0,
	"PENDING":                     1,
	"SCANNING":                    2,
	"FINISHED_SUCCESS":            3,
	"FINISHED_FAILED":             4,
	"FINISHED_UNSUPPORTED":        5,
}

func (x Discovered_AnalysisStatus) String() string {
	return proto.EnumName(Discovered_AnalysisStatus_name, int32(x))
}

func (Discovered_AnalysisStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_046437f686d0269e, []int{2, 1}
}

// DO NOT USE: UNDER HEAVY DEVELOPMENT.
// TODO(aysylu): finalize this.
//
// A note that indicates a type of analysis a provider would perform. This note
// exists in a provider's project. A `Discovery` occurrence is created in a
// consumer's project at the start of analysis.
type Discovery struct {
	// Required. Immutable. The kind of analysis that is handled by this
	// discovery.
	AnalysisKind         common_go_proto.NoteKind `protobuf:"varint,1,opt,name=analysis_kind,json=analysisKind,proto3,enum=grafeas.v1.NoteKind" json:"analysis_kind,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Discovery) Reset()         { *m = Discovery{} }
func (m *Discovery) String() string { return proto.CompactTextString(m) }
func (*Discovery) ProtoMessage()    {}
func (*Discovery) Descriptor() ([]byte, []int) {
	return fileDescriptor_046437f686d0269e, []int{0}
}

func (m *Discovery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discovery.Unmarshal(m, b)
}
func (m *Discovery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discovery.Marshal(b, m, deterministic)
}
func (m *Discovery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discovery.Merge(m, src)
}
func (m *Discovery) XXX_Size() int {
	return xxx_messageInfo_Discovery.Size(m)
}
func (m *Discovery) XXX_DiscardUnknown() {
	xxx_messageInfo_Discovery.DiscardUnknown(m)
}

var xxx_messageInfo_Discovery proto.InternalMessageInfo

func (m *Discovery) GetAnalysisKind() common_go_proto.NoteKind {
	if m != nil {
		return m.AnalysisKind
	}
	return common_go_proto.NoteKind_NOTE_KIND_UNSPECIFIED
}

// Details of a discovery occurrence.
type Details struct {
	// Required. Analysis status for the discovered resource.
	Discovered           *Discovered `protobuf:"bytes,1,opt,name=discovered,proto3" json:"discovered,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Details) Reset()         { *m = Details{} }
func (m *Details) String() string { return proto.CompactTextString(m) }
func (*Details) ProtoMessage()    {}
func (*Details) Descriptor() ([]byte, []int) {
	return fileDescriptor_046437f686d0269e, []int{1}
}

func (m *Details) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Details.Unmarshal(m, b)
}
func (m *Details) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Details.Marshal(b, m, deterministic)
}
func (m *Details) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Details.Merge(m, src)
}
func (m *Details) XXX_Size() int {
	return xxx_messageInfo_Details.Size(m)
}
func (m *Details) XXX_DiscardUnknown() {
	xxx_messageInfo_Details.DiscardUnknown(m)
}

var xxx_messageInfo_Details proto.InternalMessageInfo

func (m *Details) GetDiscovered() *Discovered {
	if m != nil {
		return m.Discovered
	}
	return nil
}

// Provides information about the analysis status of a discovered resource.
type Discovered struct {
	// Whether the resource is continuously analyzed.
	ContinuousAnalysis Discovered_ContinuousAnalysis `protobuf:"varint,1,opt,name=continuous_analysis,json=continuousAnalysis,proto3,enum=grafeas.v1.discovery.Discovered_ContinuousAnalysis" json:"continuous_analysis,omitempty"`
	// The last time continuous analysis was done for this resource.
	// Deprecated, do not use.
	LastAnalysisTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=last_analysis_time,json=lastAnalysisTime,proto3" json:"last_analysis_time,omitempty"`
	// The status of discovery for the resource.
	AnalysisStatus Discovered_AnalysisStatus `protobuf:"varint,3,opt,name=analysis_status,json=analysisStatus,proto3,enum=grafeas.v1.discovery.Discovered_AnalysisStatus" json:"analysis_status,omitempty"`
	// When an error is encountered this will contain a LocalizedMessage under
	// details to show to the user. The LocalizedMessage is output only and
	// populated by the API.
	AnalysisStatusError  *status.Status `protobuf:"bytes,4,opt,name=analysis_status_error,json=analysisStatusError,proto3" json:"analysis_status_error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Discovered) Reset()         { *m = Discovered{} }
func (m *Discovered) String() string { return proto.CompactTextString(m) }
func (*Discovered) ProtoMessage()    {}
func (*Discovered) Descriptor() ([]byte, []int) {
	return fileDescriptor_046437f686d0269e, []int{2}
}

func (m *Discovered) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discovered.Unmarshal(m, b)
}
func (m *Discovered) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discovered.Marshal(b, m, deterministic)
}
func (m *Discovered) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discovered.Merge(m, src)
}
func (m *Discovered) XXX_Size() int {
	return xxx_messageInfo_Discovered.Size(m)
}
func (m *Discovered) XXX_DiscardUnknown() {
	xxx_messageInfo_Discovered.DiscardUnknown(m)
}

var xxx_messageInfo_Discovered proto.InternalMessageInfo

func (m *Discovered) GetContinuousAnalysis() Discovered_ContinuousAnalysis {
	if m != nil {
		return m.ContinuousAnalysis
	}
	return Discovered_CONTINUOUS_ANALYSIS_UNSPECIFIED
}

func (m *Discovered) GetLastAnalysisTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastAnalysisTime
	}
	return nil
}

func (m *Discovered) GetAnalysisStatus() Discovered_AnalysisStatus {
	if m != nil {
		return m.AnalysisStatus
	}
	return Discovered_ANALYSIS_STATUS_UNSPECIFIED
}

func (m *Discovered) GetAnalysisStatusError() *status.Status {
	if m != nil {
		return m.AnalysisStatusError
	}
	return nil
}

func init() {
	proto.RegisterEnum("grafeas.v1.discovery.Discovered_ContinuousAnalysis", Discovered_ContinuousAnalysis_name, Discovered_ContinuousAnalysis_value)
	proto.RegisterEnum("grafeas.v1.discovery.Discovered_AnalysisStatus", Discovered_AnalysisStatus_name, Discovered_AnalysisStatus_value)
	proto.RegisterType((*Discovery)(nil), "grafeas.v1.discovery.Discovery")
	proto.RegisterType((*Details)(nil), "grafeas.v1.discovery.Details")
	proto.RegisterType((*Discovered)(nil), "grafeas.v1.discovery.Discovered")
}

func init() { proto.RegisterFile("proto/v1/discovery.proto", fileDescriptor_046437f686d0269e) }

var fileDescriptor_046437f686d0269e = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xdf, 0x4e, 0xdb, 0x30,
	0x18, 0xc5, 0xd7, 0xd2, 0xc1, 0xf6, 0xc1, 0x4a, 0xe4, 0x16, 0x11, 0x75, 0x17, 0x45, 0xdd, 0xcd,
	0xae, 0x1c, 0x01, 0xd2, 0xa4, 0xdd, 0x2d, 0x4b, 0x52, 0xb0, 0x40, 0x6e, 0x15, 0x27, 0xd3, 0xd8,
	0x4d, 0x94, 0xa6, 0xa1, 0x8b, 0xd6, 0xc6, 0x55, 0xec, 0x54, 0xe2, 0x31, 0xf6, 0x0a, 0x7b, 0x99,
	0xbd, 0xd6, 0x94, 0x7f, 0x1e, 0xa5, 0x48, 0x5c, 0x45, 0xdf, 0xf1, 0x77, 0x7e, 0x3e, 0x39, 0x51,
	0x40, 0x5f, 0x67, 0x5c, 0x72, 0x63, 0x73, 0x6e, 0xcc, 0x13, 0x11, 0xf1, 0x4d, 0x9c, 0x3d, 0xe0,
	0x52, 0x42, 0xfd, 0x45, 0x16, 0xde, 0xc7, 0xa1, 0xc0, 0x9b, 0x73, 0xac, 0xce, 0x06, 0xc3, 0x05,
	0xe7, 0x8b, 0x65, 0x6c, 0x94, 0x3b, 0xb3, 0xfc, 0xde, 0x90, 0xc9, 0x2a, 0x16, 0x32, 0x5c, 0xad,
	0x2b, 0xdb, 0xe0, 0xb4, 0x5e, 0xc8, 0xd6, 0x91, 0x21, 0x64, 0x28, 0x73, 0x51, 0x1f, 0x9c, 0xa8,
	0x9b, 0x22, 0xbe, 0x5a, 0xf1, 0xb4, 0x92, 0x47, 0x63, 0x78, 0x6b, 0x37, 0x74, 0xf4, 0x19, 0xde,
	0x85, 0x69, 0xb8, 0x7c, 0x10, 0x89, 0x08, 0x7e, 0x25, 0xe9, 0x5c, 0x6f, 0x9d, 0xb5, 0x3e, 0x76,
	0x2f, 0xfa, 0xf8, 0x51, 0x16, 0xca, 0x65, 0x7c, 0x93, 0xa4, 0x73, 0xf7, 0xa8, 0x59, 0x2d, 0xa6,
	0xd1, 0x0d, 0x1c, 0xd8, 0xb1, 0x0c, 0x93, 0xa5, 0x40, 0x5f, 0x00, 0x9a, 0xc0, 0x71, 0x85, 0x38,
	0xbc, 0x38, 0xc3, 0xcf, 0xbd, 0x0e, 0xb6, 0xd5, 0x9e, 0xfb, 0xc8, 0x33, 0xfa, 0xdb, 0x01, 0xf8,
	0x7f, 0x84, 0xe6, 0xd0, 0x8b, 0x78, 0x2a, 0x93, 0x34, 0xe7, 0xb9, 0x08, 0x9a, 0x6b, 0xeb, 0x70,
	0x97, 0x2f, 0x91, 0xb1, 0xa5, 0xbc, 0x66, 0x6d, 0x75, 0x51, 0xb4, 0xa3, 0xa1, 0x6b, 0x40, 0xcb,
	0x50, 0x48, 0xc5, 0x0f, 0x8a, 0x6a, 0xf5, 0x76, 0x19, 0x7f, 0x80, 0xab, 0x5a, 0x71, 0xd3, 0x3b,
	0xf6, 0x9a, 0xde, 0x5d, 0xad, 0x70, 0x35, 0x94, 0x42, 0x46, 0xdf, 0xe1, 0x58, 0x41, 0xaa, 0x6f,
	0xa0, 0xef, 0x95, 0x59, 0x8d, 0x17, 0xb3, 0x36, 0x1c, 0x56, 0xda, 0xdc, 0x6e, 0xb8, 0x35, 0xa3,
	0x31, 0x9c, 0x3c, 0x21, 0x07, 0x71, 0x96, 0xf1, 0x4c, 0xef, 0x94, 0x31, 0x51, 0x13, 0x33, 0x5b,
	0x47, 0xb8, 0x46, 0xf4, 0xb6, 0x11, 0x4e, 0xb1, 0x3e, 0x62, 0x80, 0x76, 0x5b, 0x41, 0x1f, 0x60,
	0x68, 0x4d, 0xa8, 0x47, 0xa8, 0x3f, 0xf1, 0x59, 0x60, 0x52, 0xf3, 0xf6, 0x8e, 0x11, 0x16, 0xf8,
	0x94, 0x4d, 0x1d, 0x8b, 0x8c, 0x89, 0x63, 0x6b, 0xaf, 0x10, 0xc0, 0xbe, 0x69, 0x79, 0xe4, 0x9b,
	0xa3, 0xb5, 0xd0, 0x11, 0xbc, 0x21, 0xb4, 0x9e, 0xda, 0xa3, 0xdf, 0x2d, 0xe8, 0x6e, 0xe7, 0x47,
	0x43, 0x78, 0xaf, 0x30, 0xcc, 0x33, 0x3d, 0xff, 0x29, 0xed, 0x10, 0x0e, 0xa6, 0x0e, 0xb5, 0x09,
	0xbd, 0xaa, 0x70, 0xcc, 0x32, 0x29, 0x2d, 0xa6, 0x36, 0xea, 0x83, 0x36, 0x26, 0x94, 0xb0, 0x6b,
	0xc7, 0x0e, 0x98, 0x6f, 0x59, 0x0e, 0x63, 0xda, 0x1e, 0xea, 0xc1, 0xb1, 0x52, 0xc7, 0x26, 0xb9,
	0x75, 0x6c, 0xad, 0x83, 0x74, 0xe8, 0x2b, 0xd1, 0xa7, 0xcc, 0x9f, 0x4e, 0x27, 0xae, 0xe7, 0xd8,
	0xda, 0xeb, 0xaf, 0x77, 0x70, 0x9a, 0xf0, 0x67, 0x5b, 0x9f, 0xb6, 0x7e, 0x7c, 0x5a, 0x24, 0xf2,
	0x67, 0x3e, 0xc3, 0x11, 0x5f, 0x19, 0xf5, 0x8a, 0x7a, 0xee, 0xfe, 0x97, 0xc1, 0x82, 0x07, 0xa5,
	0xfa, 0xa7, 0xbd, 0x77, 0xe5, 0x9a, 0xb3, 0xfd, 0x72, 0xb8, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff,
	0x81, 0x19, 0xea, 0x93, 0xc3, 0x03, 0x00, 0x00,
}
